import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { Navbar } from "../components/Navbar";
import { NavbarTest } from "./test/components/NavbarTest";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {/* <NavbarTest /> */}
        <Navbar />
        {children}
         <Toaster />
      </ThemeProvider>
    </main>
  );
}
